// <auto-generated />
namespace JobShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class myviewmodel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myviewmodel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091042396_myviewmodel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
